[build]
  # Instruimos a Netlify para que compile el juego automáticamente
  command = "cd Game/keepYourSheep && npm install && npm run build"
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/juego/*"
  # Redirigimos a la carpeta "build", que es donde Webpack genera los archivos finales
  to = "/Game/keepYourSheep/build/:splat"
  status = 200
