[build]
  # Esta línea es crucial para que Netlify compile tu juego
  command = "cd Game/keepYourSheep && npm install && npm run build"
  # Indica a Netlify que busque los archivos finales aquí
  publish = "Game/keepYourSheep/build"
  functions = "netlify/functions"

[[redirects]]
  from = "/juego/*"
  to = "/:splat"
  status = 200
